version: '3'

services:
  server:
    hostname: plank-server
    image: node:16-alpine
    working_dir: /home/code
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - "MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@plank-mongo:27017/admin?connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256"
      - "RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@plank-rabbitmq:5672"
      - "PLANK_SERVER_HOST=${PLANK_SERVER_HOST}"
    volumes:
      - ./server/lib:/home/code
      - ./node_modules:/home/node_modules
      - ./server/assets:/home/code/assets
      - ./server/node_modules:/home/code/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - "node"
      - "./index.js"
    networks:
      - "plank-net"
  nginx:
    hostname: plank-nginx
    image: nginx
    working_dir: /etc/nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - "${NGINX_LOCAL_PATH}/html:/usr/share/nginx/html"
      - "${NGINX_LOCAL_PATH}/conf.d:/etc/nginx/conf.d"
      - "${NGINX_LOCAL_PATH}/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "${NGINX_LOCAL_PATH}/logs:/var/log/nginx"
      - "${NGINX_LOCAL_PATH}/certs:/etc/nginx/cert"
    networks:
      - "plank-net"
  mongodb:
    hostname: plank-mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
    networks:
      - "plank-net"
  rabbitmq:
    hostname: plank-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    expose:
      - "15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}"
    networks:
      - "plank-net"

networks:
  plank-net:
